### ISSUE TITLE
Interchromosomal matrices

### ISSUE THREAD

**Issue by cmdoret** [OluwadareLab/ParticleChromo3D#1]
Hello,

I was wondering if there is a way to use whole genome (multiple chromosome) matrices with ParticleChromo3D. And if not, whether there is any plan to support that in the future.

Best

**Comment by OluwadareLab** [comment]
Thanks for asking. Currently,  ParticleChromo3D supports only intra-chromosomal 3D structure reconstruction. However, we intend on improving it to allow multiple chromosome reconstruction by adding a parameter, CHROMO_LENGTH, that accepts the size of multiple chromosomes in the input genome IF data.

**Comment by cmdoret** [comment]
Alright, thanks :)
