### ISSUE TITLE
input sparse matrix from Hi-C Pro

### ISSUE THREAD

**Issue by TerezaClarence** [OluwadareLab/ParticleChromo3D#2]
Dear Developer,

qould it be please possible to allow as input file Hi-C pro like sparse matrix in a 3-column format (bin1 bin2 IF) as in 3DMax, LorGD etc? I would greatly appreciate your help.

Secondly, would it be possibel to use ParticleChromo3D for full genome reconstruction? 

Thank you so much in advance.

Best,
Tereza

**Comment by OluwadareLab** [comment]
Hello TerezaClarence,

Thanks for usinging ParticleChromoo3D.

First, for sparse input, we can certainly make it possible for the tool to accept sparse matrix in a 3-column format.
Secondly, ParticleChromo3D currently cannot perform 3D genome reconstruction, it can only perform reconstruction per chromosome.

That said, the tool is under review for journal publication and we are making some changes to improve the tool's performance; thus, we can implement accepting sparse input as part of the update we are making. However, this update will only be available sometime in the next 1 month or less, tentatively,  according to our development timeline. You can reach out to us if you have more questions

Thanks.
OluwadareLab

**Comment by TerezaClarence** [comment]
Dear Developers of ParticleChromo 3D,

Thank you very much for your swift reply, I totally understand regarding the timeline. I will be eager to try the tool when the enhancement will be made. Thank you very much for your consideration.


Kind regards,
Tereza Clarence

From: Oluwadare Lab ***@***.***>
Date: Sunday, 26 September 2021 at 20:00
To: OluwadareLab/ParticleChromo3D ***@***.***>
Cc: Tereza Clarence ***@***.***>, Author ***@***.***>
Subject: Re: [OluwadareLab/ParticleChromo3D] input sparse matrix from Hi-C Pro (#2)

External Sender: Use caution.


Hello TerezaClarence,

Thanks for usinging ParticleChromoo3D.

First, for sparse input, we can certainly make it possible for the tool to accept sparse matrix in a 3-column format.
Secondly, ParticleChromo3D currently cannot perform 3D genome reconstruction, it can only perform reconstruction per chromosome.

That said, the tool is under review for journal publication and we are making some changes to improve the code's performance; thus, we can implement accepting sparse input as part of the update we are making. However, this update will only be available sometime in the next 1 month according to our development timeline. Please contact Dr. Oluwadare at ***@***.******@***.***> if there has been no update by then.

Thanks.
OluwadareLab

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOluwadareLab%2FParticleChromo3D%2Fissues%2F2%23issuecomment-927353805&data=04%7C01%7C%7C813ecbc73ac44bf4830e08d9811ff093%7C4eed7807ebad415aa7a99170947f4eae%7C0%7C0%7C637682796456656952%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LwIKBuEkL6qOS6cO6sTfrLU32JPBy0COsj2umNdJgvA%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHWTXYJGLKBGFUX44XKF4BDUD5UVTANCNFSM5EY2S2BA&data=04%7C01%7C%7C813ecbc73ac44bf4830e08d9811ff093%7C4eed7807ebad415aa7a99170947f4eae%7C0%7C0%7C637682796456666949%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Ks94H8Zul1Ornm1AA22BjGrmp9LJ%2FfaidX7qMw3mOAQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C813ecbc73ac44bf4830e08d9811ff093%7C4eed7807ebad415aa7a99170947f4eae%7C0%7C0%7C637682796456676942%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XCD0gDI0YHTfWtOocNZ0nzJHtmM90GQ%2Fa3EbDtDa0cw%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C813ecbc73ac44bf4830e08d9811ff093%7C4eed7807ebad415aa7a99170947f4eae%7C0%7C0%7C637682796456676942%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WW2Op%2Ff%2B2k7dslTFC6eODEbz6qINE8f8cBPw6uCN%2FAo%3D&reserved=0>.

The Francis Crick Institute Limited is a registered charity in England and Wales no. 1140062 and a company registered in England and Wales no. 06885462, with its registered office at 1 Midland Road London NW1 1AT

**Comment by DavidVadnais** [comment]
Note: The reader will not currently handle the labels in the description columns properly as it sees them as values.  Add a config parameter/function to handle this case.

**Comment by DavidVadnais** [comment]
This is handled in the latest release here: https://github.com/OluwadareLab/ParticleChromo3D_Plus/blob/main/flask/TransformVCM.py
